"""Kommune merger lookup table.

Handles the 2018 and 2020 waves of Norwegian municipality mergers and
renumberings that affect KOSTRA/SSB longitudinal data.

Each entry maps an *old* kommune number to the *new* (post-merger) number
and name.  The authoritative source is Statistisk sentralbyrå KLASS,
classification 131 (Standard for kommuneinndeling):

    https://data.ssb.no/api/klass/v1/classifications/131/changes.json

The table was generated by ``scripts/regen_kommune_mergers.py``; do not
edit the data block by hand — run that script and paste its output here.

Only 1-to-1 code changes are included (both mergers and pure renumberings
such as 0101→3001 Halden). Old codes that map to MULTIPLE new codes
(municipality splits — attribution is impossible) are excluded and listed
in ``SPLIT_CODES_EXCLUDED``.
"""

from __future__ import annotations

from typing import NamedTuple


class MergerRecord(NamedTuple):
    old_knr: str        # 4-digit zero-padded string, e.g. "1601"
    new_knr: str        # 4-digit zero-padded string
    new_name: str
    effective_year: int  # first full year as merged/renumbered municipality


# ── GENERATED DATA — do not edit by hand ─────────────────────────────────
# Source: https://data.ssb.no/api/klass/v1/classifications/131/changes.json
# Query dates: 2017-12-31→2018-01-02 (2018 wave), 2019-12-31→2020-01-02 (2020 wave)
# Fetch date: 2026-06-12
# Split-exclusion rule: old codes mapping to 2+ new codes are excluded.
# Regenerate with: uv run python scripts/regen_kommune_mergers.py

# Split codes excluded (5 total):
#   1850 -> 1806 (Narvik) / 1875 (Hábmer - Hamarøy)
#   1852 -> 1852 (Dielddanuorri - Tjeldsund) / 5412 (Dielddanuorri - Tjeldsund)
#   1903 -> 1903 (Harstad - Hárstták) / 5402 (Harstad - Hárstták)
#   1940 -> 1940 (Gáivuotna - Kåfjord - Kaivuono) / 5426 (Gáivuotna - Kåfjord - Kaivuono)
#   5012 -> 5055 (Heim) / 5056 (Hitra) / 5059 (Orkland)

SPLIT_CODES_EXCLUDED: frozenset[str] = frozenset({
    "1850",  # Tysfjord - Divtasvuodna / Narvik / Hábmer - Hamarøy
    "1852",  # Tjeldsund / Dielddanuorri - Tjeldsund
    "1903",  # Harstad / Harstad - Hárstták
    "1940",  # Gáivuotna - Kåfjord / Gáivuotna - Kåfjord - Kaivuono
    "5012",  # Snillfjord / Heim / Hitra / Orkland
})

_ALL_CHANGES: list[MergerRecord] = [  # 358 entries
    MergerRecord("0101", "3001", "Halden", 2020),
    MergerRecord("0104", "3002", "Moss", 2020),
    MergerRecord("0105", "3003", "Sarpsborg", 2020),
    MergerRecord("0106", "3004", "Fredrikstad", 2020),
    MergerRecord("0111", "3011", "Hvaler", 2020),
    MergerRecord("0118", "3012", "Aremark", 2020),
    MergerRecord("0119", "3013", "Marker", 2020),
    MergerRecord("0121", "3026", "Aurskog-Høland", 2020),
    MergerRecord("0122", "3014", "Indre Østfold", 2020),
    MergerRecord("0123", "3014", "Indre Østfold", 2020),
    MergerRecord("0124", "3014", "Indre Østfold", 2020),
    MergerRecord("0125", "3014", "Indre Østfold", 2020),
    MergerRecord("0127", "3015", "Skiptvet", 2020),
    MergerRecord("0128", "3016", "Rakkestad", 2020),
    MergerRecord("0135", "3017", "Råde", 2020),
    MergerRecord("0136", "3002", "Moss", 2020),
    MergerRecord("0137", "3018", "Våler (Viken)", 2020),
    MergerRecord("0138", "3014", "Indre Østfold", 2020),
    MergerRecord("0211", "3019", "Vestby", 2020),
    MergerRecord("0213", "3020", "Nordre Follo", 2020),
    MergerRecord("0214", "3021", "Ås", 2020),
    MergerRecord("0215", "3022", "Frogn", 2020),
    MergerRecord("0216", "3023", "Nesodden", 2020),
    MergerRecord("0217", "3020", "Nordre Follo", 2020),
    MergerRecord("0219", "3024", "Bærum", 2020),
    MergerRecord("0220", "3025", "Asker", 2020),
    MergerRecord("0221", "3026", "Aurskog-Høland", 2020),
    MergerRecord("0226", "3030", "Lillestrøm", 2020),
    MergerRecord("0227", "3030", "Lillestrøm", 2020),
    MergerRecord("0228", "3027", "Rælingen", 2020),
    MergerRecord("0229", "3028", "Enebakk", 2020),
    MergerRecord("0230", "3029", "Lørenskog", 2020),
    MergerRecord("0231", "3030", "Lillestrøm", 2020),
    MergerRecord("0233", "3031", "Nittedal", 2020),
    MergerRecord("0234", "3032", "Gjerdrum", 2020),
    MergerRecord("0235", "3033", "Ullensaker", 2020),
    MergerRecord("0236", "3034", "Nes", 2020),
    MergerRecord("0237", "3035", "Eidsvoll", 2020),
    MergerRecord("0238", "3036", "Nannestad", 2020),
    MergerRecord("0239", "3037", "Hurdal", 2020),
    MergerRecord("0402", "3401", "Kongsvinger", 2020),
    MergerRecord("0403", "3403", "Hamar", 2020),
    MergerRecord("0412", "3411", "Ringsaker", 2020),
    MergerRecord("0415", "3412", "Løten", 2020),
    MergerRecord("0417", "3413", "Stange", 2020),
    MergerRecord("0418", "3414", "Nord-Odal", 2020),
    MergerRecord("0419", "3415", "Sør-Odal", 2020),
    MergerRecord("0420", "3416", "Eidskog", 2020),
    MergerRecord("0423", "3417", "Grue", 2020),
    MergerRecord("0425", "3418", "Åsnes", 2020),
    MergerRecord("0426", "3419", "Våler (Innlandet)", 2020),
    MergerRecord("0427", "3420", "Elverum", 2020),
    MergerRecord("0428", "3421", "Trysil", 2020),
    MergerRecord("0429", "3422", "Åmot", 2020),
    MergerRecord("0430", "3423", "Stor-Elvdal", 2020),
    MergerRecord("0432", "3424", "Rendalen", 2020),
    MergerRecord("0434", "3425", "Engerdal", 2020),
    MergerRecord("0436", "3426", "Tolga", 2020),
    MergerRecord("0437", "3427", "Tynset", 2020),
    MergerRecord("0438", "3428", "Alvdal", 2020),
    MergerRecord("0439", "3429", "Folldal", 2020),
    MergerRecord("0441", "3430", "Os", 2020),
    MergerRecord("0501", "3405", "Lillehammer", 2020),
    MergerRecord("0502", "3407", "Gjøvik", 2020),
    MergerRecord("0511", "3431", "Dovre", 2020),
    MergerRecord("0512", "3432", "Lesja", 2020),
    MergerRecord("0513", "3433", "Skjåk", 2020),
    MergerRecord("0514", "3434", "Lom", 2020),
    MergerRecord("0515", "3435", "Vågå", 2020),
    MergerRecord("0516", "3436", "Nord-Fron", 2020),
    MergerRecord("0517", "3437", "Sel", 2020),
    MergerRecord("0519", "3438", "Sør-Fron", 2020),
    MergerRecord("0520", "3439", "Ringebu", 2020),
    MergerRecord("0521", "3440", "Øyer", 2020),
    MergerRecord("0522", "3441", "Gausdal", 2020),
    MergerRecord("0528", "3442", "Østre Toten", 2020),
    MergerRecord("0529", "3443", "Vestre Toten", 2020),
    MergerRecord("0532", "3053", "Jevnaker", 2020),
    MergerRecord("0533", "3054", "Lunner", 2020),
    MergerRecord("0534", "3446", "Gran", 2020),
    MergerRecord("0536", "3447", "Søndre Land", 2020),
    MergerRecord("0538", "3448", "Nordre Land", 2020),
    MergerRecord("0540", "3449", "Sør-Aurdal", 2020),
    MergerRecord("0541", "3450", "Etnedal", 2020),
    MergerRecord("0542", "3451", "Nord-Aurdal", 2020),
    MergerRecord("0543", "3452", "Vestre Slidre", 2020),
    MergerRecord("0544", "3453", "Øystre Slidre", 2020),
    MergerRecord("0545", "3454", "Vang", 2020),
    MergerRecord("0602", "3005", "Drammen", 2020),
    MergerRecord("0604", "3006", "Kongsberg", 2020),
    MergerRecord("0605", "3007", "Ringerike", 2020),
    MergerRecord("0612", "3038", "Hole", 2020),
    MergerRecord("0615", "3039", "Flå", 2020),
    MergerRecord("0616", "3040", "Nesbyen", 2020),
    MergerRecord("0617", "3041", "Gol", 2020),
    MergerRecord("0618", "3042", "Hemsedal", 2020),
    MergerRecord("0619", "3043", "Ål", 2020),
    MergerRecord("0620", "3044", "Hol", 2020),
    MergerRecord("0621", "3045", "Sigdal", 2020),
    MergerRecord("0622", "3046", "Krødsherad", 2020),
    MergerRecord("0623", "3047", "Modum", 2020),
    MergerRecord("0624", "3048", "Øvre Eiker", 2020),
    MergerRecord("0625", "3005", "Drammen", 2020),
    MergerRecord("0626", "3049", "Lier", 2020),
    MergerRecord("0627", "3025", "Asker", 2020),
    MergerRecord("0628", "3025", "Asker", 2020),
    MergerRecord("0631", "3050", "Flesberg", 2020),
    MergerRecord("0632", "3051", "Rollag", 2020),
    MergerRecord("0633", "3052", "Nore og Uvdal", 2020),
    MergerRecord("0701", "3801", "Horten", 2020),
    MergerRecord("0702", "0715", "Holmestrand", 2018),
    MergerRecord("0704", "3803", "Tønsberg", 2020),
    MergerRecord("0709", "0712", "Larvik", 2018),
    MergerRecord("0710", "3804", "Sandefjord", 2020),
    MergerRecord("0711", "3005", "Drammen", 2020),
    MergerRecord("0712", "3805", "Larvik", 2020),
    MergerRecord("0713", "3802", "Holmestrand", 2020),
    MergerRecord("0714", "0715", "Holmestrand", 2018),
    MergerRecord("0715", "3802", "Holmestrand", 2020),
    MergerRecord("0716", "3803", "Tønsberg", 2020),
    MergerRecord("0722", "0729", "Færder", 2018),
    MergerRecord("0723", "0729", "Færder", 2018),
    MergerRecord("0728", "0712", "Larvik", 2018),
    MergerRecord("0729", "3811", "Færder", 2020),
    MergerRecord("0805", "3806", "Porsgrunn", 2020),
    MergerRecord("0806", "3807", "Skien", 2020),
    MergerRecord("0807", "3808", "Notodden", 2020),
    MergerRecord("0811", "3812", "Siljan", 2020),
    MergerRecord("0814", "3813", "Bamble", 2020),
    MergerRecord("0815", "3814", "Kragerø", 2020),
    MergerRecord("0817", "3815", "Drangedal", 2020),
    MergerRecord("0819", "3816", "Nome", 2020),
    MergerRecord("0821", "3817", "Midt-Telemark", 2020),
    MergerRecord("0822", "3817", "Midt-Telemark", 2020),
    MergerRecord("0826", "3818", "Tinn", 2020),
    MergerRecord("0827", "3819", "Hjartdal", 2020),
    MergerRecord("0828", "3820", "Seljord", 2020),
    MergerRecord("0829", "3821", "Kviteseid", 2020),
    MergerRecord("0830", "3822", "Nissedal", 2020),
    MergerRecord("0831", "3823", "Fyresdal", 2020),
    MergerRecord("0833", "3824", "Tokke", 2020),
    MergerRecord("0834", "3825", "Vinje", 2020),
    MergerRecord("0901", "4201", "Risør", 2020),
    MergerRecord("0904", "4202", "Grimstad", 2020),
    MergerRecord("0906", "4203", "Arendal", 2020),
    MergerRecord("0911", "4211", "Gjerstad", 2020),
    MergerRecord("0912", "4212", "Vegårshei", 2020),
    MergerRecord("0914", "4213", "Tvedestrand", 2020),
    MergerRecord("0919", "4214", "Froland", 2020),
    MergerRecord("0926", "4215", "Lillesand", 2020),
    MergerRecord("0928", "4216", "Birkenes", 2020),
    MergerRecord("0929", "4217", "Åmli", 2020),
    MergerRecord("0935", "4218", "Iveland", 2020),
    MergerRecord("0937", "4219", "Evje og Hornnes", 2020),
    MergerRecord("0938", "4220", "Bygland", 2020),
    MergerRecord("0940", "4221", "Valle", 2020),
    MergerRecord("0941", "4222", "Bykle", 2020),
    MergerRecord("1001", "4204", "Kristiansand", 2020),
    MergerRecord("1002", "4205", "Lindesnes", 2020),
    MergerRecord("1003", "4206", "Farsund", 2020),
    MergerRecord("1004", "4207", "Flekkefjord", 2020),
    MergerRecord("1014", "4223", "Vennesla", 2020),
    MergerRecord("1017", "4204", "Kristiansand", 2020),
    MergerRecord("1018", "4204", "Kristiansand", 2020),
    MergerRecord("1021", "4205", "Lindesnes", 2020),
    MergerRecord("1026", "4224", "Åseral", 2020),
    MergerRecord("1027", "4225", "Lyngdal", 2020),
    MergerRecord("1029", "4205", "Lindesnes", 2020),
    MergerRecord("1032", "4225", "Lyngdal", 2020),
    MergerRecord("1034", "4226", "Hægebostad", 2020),
    MergerRecord("1037", "4227", "Kvinesdal", 2020),
    MergerRecord("1046", "4228", "Sirdal", 2020),
    MergerRecord("1102", "1108", "Sandnes", 2020),
    MergerRecord("1129", "1108", "Sandnes", 2020),
    MergerRecord("1141", "1103", "Stavanger", 2020),
    MergerRecord("1142", "1103", "Stavanger", 2020),
    MergerRecord("1201", "4601", "Bergen", 2020),
    MergerRecord("1211", "4611", "Etne", 2020),
    MergerRecord("1216", "4612", "Sveio", 2020),
    MergerRecord("1219", "4613", "Bømlo", 2020),
    MergerRecord("1221", "4614", "Stord", 2020),
    MergerRecord("1222", "4615", "Fitjar", 2020),
    MergerRecord("1223", "4616", "Tysnes", 2020),
    MergerRecord("1224", "4617", "Kvinnherad", 2020),
    MergerRecord("1227", "4618", "Ullensvang", 2020),
    MergerRecord("1228", "4618", "Ullensvang", 2020),
    MergerRecord("1231", "4618", "Ullensvang", 2020),
    MergerRecord("1232", "4619", "Eidfjord", 2020),
    MergerRecord("1233", "4620", "Ulvik", 2020),
    MergerRecord("1234", "4621", "Voss", 2020),
    MergerRecord("1235", "4621", "Voss", 2020),
    MergerRecord("1238", "4622", "Kvam", 2020),
    MergerRecord("1241", "4624", "Bjørnafjorden", 2020),
    MergerRecord("1242", "4623", "Samnanger", 2020),
    MergerRecord("1243", "4624", "Bjørnafjorden", 2020),
    MergerRecord("1244", "4625", "Austevoll", 2020),
    MergerRecord("1245", "4626", "Øygarden", 2020),
    MergerRecord("1246", "4626", "Øygarden", 2020),
    MergerRecord("1247", "4627", "Askøy", 2020),
    MergerRecord("1251", "4628", "Vaksdal", 2020),
    MergerRecord("1252", "4629", "Modalen", 2020),
    MergerRecord("1253", "4630", "Osterøy", 2020),
    MergerRecord("1256", "4631", "Alver", 2020),
    MergerRecord("1259", "4626", "Øygarden", 2020),
    MergerRecord("1260", "4631", "Alver", 2020),
    MergerRecord("1263", "4631", "Alver", 2020),
    MergerRecord("1264", "4632", "Austrheim", 2020),
    MergerRecord("1265", "4633", "Fedje", 2020),
    MergerRecord("1266", "4634", "Masfjorden", 2020),
    MergerRecord("1401", "4602", "Kinn", 2020),
    MergerRecord("1411", "4635", "Gulen", 2020),
    MergerRecord("1412", "4636", "Solund", 2020),
    MergerRecord("1413", "4637", "Hyllestad", 2020),
    MergerRecord("1416", "4638", "Høyanger", 2020),
    MergerRecord("1417", "4639", "Vik", 2020),
    MergerRecord("1418", "4640", "Sogndal", 2020),
    MergerRecord("1419", "4640", "Sogndal", 2020),
    MergerRecord("1420", "4640", "Sogndal", 2020),
    MergerRecord("1421", "4641", "Aurland", 2020),
    MergerRecord("1422", "4642", "Lærdal", 2020),
    MergerRecord("1424", "4643", "Årdal", 2020),
    MergerRecord("1426", "4644", "Luster", 2020),
    MergerRecord("1428", "4645", "Askvoll", 2020),
    MergerRecord("1429", "4646", "Fjaler", 2020),
    MergerRecord("1430", "4647", "Sunnfjord", 2020),
    MergerRecord("1431", "4647", "Sunnfjord", 2020),
    MergerRecord("1432", "4647", "Sunnfjord", 2020),
    MergerRecord("1433", "4647", "Sunnfjord", 2020),
    MergerRecord("1438", "4648", "Bremanger", 2020),
    MergerRecord("1439", "4602", "Kinn", 2020),
    MergerRecord("1441", "4649", "Stad", 2020),
    MergerRecord("1443", "4649", "Stad", 2020),
    MergerRecord("1444", "1577", "Volda", 2020),
    MergerRecord("1445", "4650", "Gloppen", 2020),
    MergerRecord("1449", "4651", "Stryn", 2020),
    MergerRecord("1502", "1506", "Molde", 2020),
    MergerRecord("1504", "1507", "Ålesund", 2020),
    MergerRecord("1519", "1577", "Volda", 2020),
    MergerRecord("1523", "1507", "Ålesund", 2020),
    MergerRecord("1524", "1578", "Fjord", 2020),
    MergerRecord("1526", "1578", "Fjord", 2020),
    MergerRecord("1529", "1507", "Ålesund", 2020),
    MergerRecord("1534", "1507", "Ålesund", 2020),
    MergerRecord("1543", "1506", "Molde", 2020),
    MergerRecord("1545", "1506", "Molde", 2020),
    MergerRecord("1546", "1507", "Ålesund", 2020),
    MergerRecord("1548", "1579", "Hustadvika", 2020),
    MergerRecord("1551", "1579", "Hustadvika", 2020),
    MergerRecord("1571", "5055", "Heim", 2020),
    MergerRecord("1601", "5001", "Trondheim", 2018),
    MergerRecord("1612", "5011", "Hemne", 2018),
    MergerRecord("1613", "5012", "Snillfjord", 2018),
    MergerRecord("1617", "5013", "Hitra", 2018),
    MergerRecord("1620", "5014", "Frøya", 2018),
    MergerRecord("1621", "5015", "Ørland", 2018),
    MergerRecord("1622", "5016", "Agdenes", 2018),
    MergerRecord("1624", "5054", "Indre Fosen", 2018),
    MergerRecord("1627", "5017", "Bjugn", 2018),
    MergerRecord("1630", "5018", "Åfjord", 2018),
    MergerRecord("1632", "5019", "Roan", 2018),
    MergerRecord("1633", "5020", "Osen", 2018),
    MergerRecord("1634", "5021", "Oppdal", 2018),
    MergerRecord("1635", "5022", "Rennebu", 2018),
    MergerRecord("1636", "5023", "Meldal", 2018),
    MergerRecord("1638", "5024", "Orkdal", 2018),
    MergerRecord("1640", "5025", "Røros", 2018),
    MergerRecord("1644", "5026", "Holtålen", 2018),
    MergerRecord("1648", "5027", "Midtre Gauldal", 2018),
    MergerRecord("1653", "5028", "Melhus", 2018),
    MergerRecord("1657", "5029", "Skaun", 2018),
    MergerRecord("1662", "5030", "Klæbu", 2018),
    MergerRecord("1663", "5031", "Malvik", 2018),
    MergerRecord("1664", "5032", "Selbu", 2018),
    MergerRecord("1665", "5033", "Tydal", 2018),
    MergerRecord("1702", "5004", "Steinkjer", 2018),
    MergerRecord("1703", "5005", "Namsos", 2018),
    MergerRecord("1711", "5034", "Meråker", 2018),
    MergerRecord("1714", "5035", "Stjørdal", 2018),
    MergerRecord("1717", "5036", "Frosta", 2018),
    MergerRecord("1718", "5054", "Indre Fosen", 2018),
    MergerRecord("1719", "5037", "Levanger", 2018),
    MergerRecord("1721", "5038", "Verdal", 2018),
    MergerRecord("1724", "5039", "Verran", 2018),
    MergerRecord("1725", "5040", "Namdalseid", 2018),
    MergerRecord("1736", "5041", "Snåase - Snåsa", 2018),
    MergerRecord("1738", "5042", "Lierne", 2018),
    MergerRecord("1739", "5043", "Raarvihke - Røyrvik", 2018),
    MergerRecord("1740", "5044", "Namsskogan", 2018),
    MergerRecord("1742", "5045", "Grong", 2018),
    MergerRecord("1743", "5046", "Høylandet", 2018),
    MergerRecord("1744", "5047", "Overhalla", 2018),
    MergerRecord("1748", "5048", "Fosnes", 2018),
    MergerRecord("1749", "5049", "Flatanger", 2018),
    MergerRecord("1750", "5050", "Vikna", 2018),
    MergerRecord("1751", "5051", "Nærøy", 2018),
    MergerRecord("1755", "5052", "Leka", 2018),
    MergerRecord("1756", "5053", "Inderøy", 2018),
    MergerRecord("1805", "1806", "Narvik", 2020),
    MergerRecord("1849", "1875", "Hábmer - Hamarøy", 2020),
    MergerRecord("1854", "1806", "Narvik", 2020),
    MergerRecord("1902", "5401", "Tromsø", 2020),
    MergerRecord("1911", "5411", "Kvæfjord", 2020),
    MergerRecord("1913", "5412", "Dielddanuorri - Tjeldsund", 2020),
    MergerRecord("1917", "5413", "Ibestad", 2020),
    MergerRecord("1919", "5414", "Gratangen", 2020),
    MergerRecord("1920", "5415", "Loabák - Lavangen", 2020),
    MergerRecord("1922", "5416", "Bardu", 2020),
    MergerRecord("1923", "5417", "Salangen", 2020),
    MergerRecord("1924", "5418", "Målselv", 2020),
    MergerRecord("1925", "5419", "Sørreisa", 2020),
    MergerRecord("1926", "5420", "Dyrøy", 2020),
    MergerRecord("1927", "5421", "Senja", 2020),
    MergerRecord("1928", "5421", "Senja", 2020),
    MergerRecord("1929", "5421", "Senja", 2020),
    MergerRecord("1931", "5421", "Senja", 2020),
    MergerRecord("1933", "5422", "Balsfjord", 2020),
    MergerRecord("1936", "5423", "Karlsøy", 2020),
    MergerRecord("1938", "5424", "Lyngen", 2020),
    MergerRecord("1939", "5425", "Storfjord - Omasvuotna - Omasvuono", 2020),
    MergerRecord("1941", "5427", "Skjervøy", 2020),
    MergerRecord("1942", "5428", "Nordreisa - Ráisa - Raisi", 2020),
    MergerRecord("1943", "5429", "Kvænangen", 2020),
    MergerRecord("2002", "5404", "Vardø", 2020),
    MergerRecord("2003", "5405", "Vadsø", 2020),
    MergerRecord("2004", "5406", "Hammerfest - Hámmerfeasta", 2020),
    MergerRecord("2011", "5430", "Guovdageaidnu - Kautokeino", 2020),
    MergerRecord("2012", "5403", "Alta", 2020),
    MergerRecord("2014", "5432", "Loppa", 2020),
    MergerRecord("2015", "5433", "Hasvik", 2020),
    MergerRecord("2017", "5406", "Hammerfest - Hámmerfeasta", 2020),
    MergerRecord("2018", "5434", "Måsøy", 2020),
    MergerRecord("2019", "5435", "Nordkapp", 2020),
    MergerRecord("2020", "5436", "Porsanger - Porsángu - Porsanki", 2020),
    MergerRecord("2021", "5437", "Kárášjohka - Karasjok", 2020),
    MergerRecord("2022", "5438", "Lebesby", 2020),
    MergerRecord("2023", "5439", "Gamvik", 2020),
    MergerRecord("2024", "5440", "Berlevåg", 2020),
    MergerRecord("2025", "5441", "Deatnu - Tana", 2020),
    MergerRecord("2027", "5442", "Unjárga - Nesseby", 2020),
    MergerRecord("2028", "5443", "Båtsfjord", 2020),
    MergerRecord("2030", "5444", "Sør-Varanger", 2020),
    MergerRecord("5004", "5006", "Steinkjer", 2020),
    MergerRecord("5005", "5007", "Namsos - Nåavmesjenjaelmie", 2020),
    MergerRecord("5011", "5055", "Heim", 2020),
    MergerRecord("5013", "5056", "Hitra", 2020),
    MergerRecord("5015", "5057", "Ørland", 2020),
    MergerRecord("5016", "5059", "Orkland", 2020),
    MergerRecord("5017", "5057", "Ørland", 2020),
    MergerRecord("5018", "5058", "Åfjord", 2020),
    MergerRecord("5019", "5058", "Åfjord", 2020),
    MergerRecord("5023", "5059", "Orkland", 2020),
    MergerRecord("5024", "5059", "Orkland", 2020),
    MergerRecord("5030", "5001", "Trondheim", 2020),
    MergerRecord("5039", "5006", "Steinkjer", 2020),
    MergerRecord("5040", "5007", "Namsos - Nåavmesjenjaelmie", 2020),
    MergerRecord("5048", "5007", "Namsos - Nåavmesjenjaelmie", 2020),
    MergerRecord("5050", "5060", "Nærøysund", 2020),
    MergerRecord("5051", "5060", "Nærøysund", 2020),
]

# Build lookup dict: old_knr → new_knr
MERGER_LOOKUP: dict[str, str] = {r.old_knr: r.new_knr for r in _ALL_CHANGES}

# Reverse map: new_knr → list of old_knrs (for provenance)
REVERSE_MERGER_LOOKUP: dict[str, list[str]] = {}
for r in _ALL_CHANGES:
    REVERSE_MERGER_LOOKUP.setdefault(r.new_knr, []).append(r.old_knr)

# Name lookup by new_knr
MUNICIPALITY_NAMES: dict[str, str] = {r.new_knr: r.new_name for r in _ALL_CHANGES}


def normalize_knr(knr: str) -> str:
    """Return the current (post-merger/renumbering) kommune number for a given input.

    If *knr* is an old pre-merger number, return the successor.
    Codes in ``SPLIT_CODES_EXCLUDED`` are returned unchanged (attribution
    is impossible for splits). Otherwise return *knr* unchanged.

    Args:
        knr: 4-digit zero-padded municipality code (string).

    Returns:
        Current 4-digit municipality code.
    """
    knr = knr.strip().zfill(4)
    return MERGER_LOOKUP.get(knr, knr)


def normalize_knr_series(series: "pd.Series") -> "pd.Series":  # type: ignore[name-defined]
    """Vectorized version of :func:`normalize_knr` for a pandas Series."""
    return series.astype(str).str.strip().str.zfill(4).map(
        lambda k: MERGER_LOOKUP.get(k, k)
    )
