"""Offline e2e integration test for the brfss-demo analysis instance.

No network, no spaCy NER model — uses the committed brfss_sample.csv fixture
(generated by make_fixture.py). Verifies the full ingest → profile → anonymize
→ analyze → verify → report pipeline with all gate assertions.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from omsorgsradar.core.anonymize.pii import append_fnr_control_digits
from omsorgsradar.pipeline import run_pipeline

BRFSS_ANALYSIS_DIR = (
    Path(__file__).parent.parent / "analyses" / "brfss-demo"
)
MICRODATA_DIR = BRFSS_ANALYSIS_DIR / "microdata"
FIXTURE_CSV = MICRODATA_DIR / "brfss_sample.csv"


def _valid_fnr(ddmmyy: str, start_individ: int = 100) -> str:
    """Return a checksum-valid fnr for a birth date (mirrors make_fixture._valid_fnr)."""
    for ind in range(start_individ, 1000):
        try:
            return append_fnr_control_digits(f"{ddmmyy}{ind:03d}")
        except ValueError:
            continue
    raise RuntimeError("no valid individ found")


def _ensure_fixture() -> None:
    """Regenerate brfss_sample.csv into the real microdata/ dir if missing."""
    if not FIXTURE_CSV.exists():
        import sys
        sys.path.insert(0, str(BRFSS_ANALYSIS_DIR / "microdata"))
        import make_fixture  # type: ignore[import]
        df = make_fixture.build()
        FIXTURE_CSV.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(FIXTURE_CSV, index=False)


@pytest.fixture(scope="module")
def pipeline_output(tmp_path_factory: pytest.TempPathFactory):
    """Run the full brfss-demo pipeline once; share results across all tests."""
    _ensure_fixture()
    tmp = tmp_path_factory.mktemp("brfss_e2e")
    data_dir = tmp / "data"
    reports_dir = tmp / "reports"
    runs_dir = tmp / "runs"

    run_pipeline(
        BRFSS_ANALYSIS_DIR,
        data_dir=data_dir,
        reports_dir=reports_dir,
        runs_dir=runs_dir,
    )
    return {
        "data_dir": data_dir,
        "reports_dir": reports_dir,
        "runs_dir": runs_dir,
    }


class TestBrfssDemoIntegration:
    def test_report_exists_and_contains_residual_risk(self, pipeline_output):
        report_path = pipeline_output["reports_dir"] / "brfss-demo_rapport.md"
        assert report_path.exists(), "brfss-demo_rapport.md was not produced"
        text = report_path.read_text(encoding="utf-8")
        assert "målt restrisiko" in text, "Report does not contain 'målt restrisiko'"

    def test_report_contains_wp216_criteria(self, pipeline_output):
        report_path = pipeline_output["reports_dir"] / "brfss-demo_rapport.md"
        text = report_path.read_text(encoding="utf-8")
        # All three WP216 criterion names must appear
        for word in ("singling-out", "linkability", "inference"):
            assert word in text.lower() or word in text, (
                f"Report missing WP216 criterion word: '{word}'"
            )

    def test_identifiability_verdict_pass_or_warn(self, pipeline_output):
        receipt_path = pipeline_output["data_dir"] / "identifiability.json"
        assert receipt_path.exists(), "identifiability.json not written"
        receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
        assert receipt["verdict"] in {"PASS", "WARN"}, (
            f"identifiability verdict must be PASS or WARN, got: {receipt['verdict']}"
        )

    def test_planted_fnr_absent_from_anonymized_csv(self, pipeline_output):
        anon_path = pipeline_output["data_dir"] / "brfss_anonymized.csv"
        assert anon_path.exists(), "brfss_anonymized.csv not written"
        anon_text = anon_path.read_text(encoding="utf-8")
        planted = _valid_fnr("010190")
        assert planted not in anon_text, (
            f"Planted fnr {planted} still present in brfss_anonymized.csv — redaction failed"
        )

    def test_min_class_size_at_least_k(self, pipeline_output):
        receipt_path = pipeline_output["data_dir"] / "identifiability.json"
        receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
        k_info = receipt.get("k_anonymity", {})
        min_class = k_info.get("min_class_size", 0)
        k_target = k_info.get("k_target", 10)
        assert min_class >= k_target, (
            f"min_class_size={min_class} < k_target={k_target}: k-anonymity violated"
        )

    def test_verification_verdict_pass(self, pipeline_output):
        verif_path = pipeline_output["data_dir"] / "verification.json"
        assert verif_path.exists(), "verification.json not written"
        verif = json.loads(verif_path.read_text(encoding="utf-8"))
        assert verif["verdict"] == "PASS", (
            f"verification verdict must be PASS, got: {verif['verdict']} — "
            f"failures: {verif.get('failures', [])}"
        )

    def test_journal_status_ok_and_stage_order(self, pipeline_output):
        runs_dir = pipeline_output["runs_dir"]
        run_files = list(runs_dir.glob("*/run.json"))
        assert run_files, "No run.json found under runs_dir"
        run_json = json.loads(run_files[0].read_text(encoding="utf-8"))

        assert run_json.get("status") == "ok", (
            f"Journal run status must be 'ok', got: {run_json.get('status')}"
        )

        stages = [s["stage"] for s in run_json.get("stages", [])]
        assert "anonymize" in stages, "anonymize stage not recorded in journal"
        if "profile" in stages and "analyze" in stages:
            profile_idx = stages.index("profile")
            anon_idx = stages.index("anonymize")
            analyze_idx = stages.index("analyze")
            assert profile_idx < anon_idx < analyze_idx, (
                f"Stage order wrong: profile={profile_idx}, "
                f"anonymize={anon_idx}, analyze={analyze_idx}"
            )
